[tools]
node = "latest"
python = "3.12.4"
ruby = "3.2.2"
usage = "latest"
chezmoi = "2.65.1"
rust = "latest"
cargo-binstall = "latest"
"npm:eslint_d" = "14.0.3"
"npm:typescript" = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:ripgrep" = "latest"
"cargo:sd" = "latest"
"cargo:starship" = "latest"
"cargo:ubi-cli" = "latest"
"cargo:zellij" = "latest"
"ubi:casey/just" = "latest"
"ubi:dandavison/delta" = "latest"
"ubi:jqlang/jq" = "latest"
"ubi:junegunn/fzf" = { version = "latest" }
"ubi:koalaman/shellcheck" = "latest"
"ubi:neovim/neovim" = { version = "latest", exe = "nvim", extract_all = true, bin_path = "bin" }
"ubi:cli/cli" = { version = "latest", exe = "gh" }
"ubi:simeji/jid" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@github/copilot" = "latest"
colima = "latest"
lima = "latest"
docker-compose = "latest"
docker-cli = "latest"
"cargo:tree-sitter-cli" = "latest"

[settings]
experimental = true
status.show_env = true
status.show_tools = true

[env]
CLOUDSDK_ACTIVE_CONFIG_NAME = 'default'
